import { Navigation } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/footer";
import Provider from './components/provider';
import "./globals.css";
import ConditionalNav from './components/ConditionalNav';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased`} 
      >
        <Provider>
          <ConditionalNav />
          {children}
        </Provider>
        
        {/*footer*/}
        <Footer/>
      </body>
    </html>
  );
}
